
spring:
  datasource:
    druid:
      connection-properties: "config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}"
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      async-init: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,slf4j

mybatis:
  mapper-locations: classpath*:com/nice/sboot/**/*.xml
#  config-location: classpath:xml/mybatis-config.xml
  type-aliases-package: com.nice.sboot.auth.entity
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
#  reasonable: true
#  page-size-zero: true
#  offset-as-page-num: true
  support-methods-arguments: true

# dubbo 通用配置
dubbo:
  scan:
    base-packages: com.nice
  application:
    name: ${spring.application.name}
  provider:
    delay: -1
    timeout: 20000
  consumer:
    lazy: true
    timeout: 20000
    check: false
    retries: 2
    loadbalance: leastactive
  registry:
    protocol: zookeeper
    client: curator
    check: false
  protocol:
    name: dubbo
    serialization: kryo
#    optimizer: 实现性能更佳
    port: -1
    threads: 300
