
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: fI1jQenplbnfUS5plboe3ZabIM8/S8f0FLUn52cTq3cHsINUSi0pEOGYvRENDNbpY+fNXjAjnqj/+pbv8z/k5Q==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJPBhbJk7I8jDi9AEFyu4WNK7RhbsPdI1+0Jws3D/nZiH1F/kdLIXGNmPYkq/urxVxd641Tea5ZKpxObpvB3KIUCAwEAAQ==
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      async-init: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,slf4j,wall
      filter:
        wall:
          enabled: true
          db-type: mysql
          config:
            delete-allow: false
            drop-table-allow: false
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

  redis:
    password: pwd
    timeout: 3000
    cluster:
      max-redirects: 3
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 32
        max-wait: 600000ms
