
spring:
  redis:
    password: pwd
    timeout: 3000
    cluster:
      max-redirects: 3
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 32
        max-wait: 600000ms

  thymeleaf:
    cache: false
