
spring:
  profiles: env

  redis:
    password: luoyong123
    timeout: PT3S
    cluster:
      max-redirects: 3
      nodes: 192.168.3.9:7001,192.168.3.9:7002,192.168.3.9:7003,192.168.3.9:7004,192.168.3.9:7005,192.168.3.9:7006
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 32
        max-wait: 600000ms

swagger:
  api:
    title: 接口文档-demo
    description: demo接口文档，包括PC,H5,APP相关的接口
    base-package: com.nice.sboot
  mapping:
    path: /
