
spring:
  datasource:
    druid:
#      url: jdbc:h2:mem:testdb
      url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE
      username: sa
      password: XHvxm/oKfNJb9g+Kz8Y8FRvaDOmx3l3UnDd0arniSV2HsSoSDbebBiEppBdVmKtdF6ZZErH69x4cLLRV3Ts4Dw==
      public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAI4N6qzc3sO+KY7tY0ViCrmfjH05Ej0/1QEuw64NLo6fSkjY6vEBcMusnN2RLEyZq254x1dinL92ayXc8EAItDkCAwEAAQ==
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      async-init: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,slf4j,wall
      filter:
        wall:
          enabled: true
          db-type: h2
          config:
            delete-allow: false
            drop-table-allow: false
        stat:
          enabled: true
          db-type: h2
          log-slow-sql: true
          slow-sql-millis: 2000

  data:
    mongodb:
      uri: mongodb://testdb:123456a@localhost:27017/testdb

  redis:
    password: pwd
    timeout: 3000
    cluster:
      max-redirects: 3
      nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003,127.0.0.1:7004,127.0.0.1:7005,127.0.0.1:7006
    lettuce:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 32
        max-wait: 600000ms
