
spring:
  datasource:
    druid:
      connection-properties: "config.decrypt=true;config.decrypt.key=${spring.datasource.druid.public-key}"
      initial-size: 5
      max-active: 100
      min-idle: 10
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      filters: config,stat,slf4j

